environment:
  matrix:
  - TARGET: x86_64-pc-windows-gnu
    CHANNEL: stable
  - TARGET: i686-pc-windows-gnu
    CHANNEL: stable
  - TARGET: x86_64-pc-windows-msvc
    CHANNEL: stable
  - TARGET: i686-pc-windows-msvc
    CHANNEL: stable

install:
  - curl -sSf -o rustup-init.exe https://win.rustup.rs
  - rustup-init.exe --default-host %TARGET% --default-toolchain %CHANNEL% -y
  - set PATH=%PATH%;C:\Users\appveyor\.cargo\bin
  - rustc -Vv
  - cargo -V

platform: Any CPU

notifications:
  - provider: Email
    to:
      - cassiokirch@gmail.com
    #subject: 'Build {{status}}'                  # optional
    #message: "{{message}}, {{commitId}}, ..."    # optional
    on_build_success: true
    on_build_failure: true
    on_build_status_changed: true

build: false

test_script:
  - cargo test --verbose --all
  - cargo build --verbose --all
